# Generated by Django 4.1.1 on 2022-09-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVCExemplo', '0002_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='curso',
        ),
    ]
