# Generated by Django 4.1.1 on 2022-09-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MVCExemplo', '0003_remove_estudante_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MVCExemplo.curso'),
        ),
    ]
