# Generated by Django 4.1.1 on 2022-09-17 17:53

from django.db import migrations

def popule_sistema_operacional(apps, schema_editor):
    SistemaOperacional = apps.get_model('MVCExemplo', 'SistemaOperacional')
    SistemaOperacional.objects.create(nome='Windows')
    SistemaOperacional.objects.create(nome='Linux')
    SistemaOperacional.objects.create(nome='MacOS')

def popule_curso(apps, schema_editor):
    Curso = apps.get_model('MVCExemplo', 'Curso')
    Curso.objects.create(nome='Engenharia de Software')
    Curso.objects.create(nome='Ciência da Computação')
    Curso.objects.create(nome='Tecnologia da Informação')

class Migration(migrations.Migration):

    dependencies = [
        ('MVCExemplo', '0004_estudante_curso'),
    ]

    operations = [
        migrations.RunPython(popule_sistema_operacional),
        migrations.RunPython(popule_curso),
    ]
