# Generated by Django 4.1.1 on 2022-09-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MVCExemplo', '0006_linguagem_remove_estudante_linguagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='linguagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MVCExemplo.linguagem'),
        ),
    ]
