# Generated by Django 4.1.1 on 2022-09-17 18:09

from django.db import migrations

def popule_linguagem(apps, schema_editor):
    Linguagem = apps.get_model('MVCExemplo', 'Linguagem')
    Linguagem.objects.create(nome='Python')
    Linguagem.objects.create(nome='Java')
    Linguagem.objects.create(nome='C#')
    Linguagem.objects.create(nome='C++')
    Linguagem.objects.create(nome='C')
    Linguagem.objects.create(nome='JavaScript')
    Linguagem.objects.create(nome='TypeScript')

class Migration(migrations.Migration):

    dependencies = [
        ('MVCExemplo', '0007_estudante_linguagem'),
    ]

    operations = [
        migrations.RunPython(popule_linguagem),
    ]
