# Generated by Django 4.1.1 on 2022-09-21 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MVCAppData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MVCAppData.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='MVCAppData.subject', verbose_name='Disciplinas'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=7, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVCAppData.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Disciplina'),
        ),
    ]
