# Generated by Django 4.1.1 on 2022-09-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVCAppData', '0003_alter_student_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
    ]
