# Generated by Django 4.1.1 on 2022-09-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVCAppData', '0004_remove_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='MVCAppData.subject', verbose_name='Disciplinas'),
        ),
    ]
